# -*- coding: utf-8 -*-
"""鉴权测试：AUTH_ENABLED 开/关两条路径 + request_id 透传/自动生成。

- 默认 client fixture：鉴权关闭（无 token 也放行）；
- auth_client fixture：鉴权开启（无/错 token 拒绝，正确 token 放行）。
"""

from __future__ import annotations

from tests.conftest import make_success_body, make_chunk

URL = "/api/v1/navigator/query"


def _payload():
    return {
        "query": "a.docx",
        "options": {},
    }


# =====================================================================
# 鉴权关闭（默认 client）
# =====================================================================

def test_auth_disabled_no_token_passes(client, fake_client):
    fake_client.set_script(make_success_body([make_chunk(0, "A"), make_chunk(1, "B")]))
    resp = client.post(URL, json=_payload())
    assert resp.status_code == 200
    assert resp.json()["code"] == 200


# =====================================================================
# 鉴权开启（auth_client）
# =====================================================================

def test_auth_enabled_missing_token_rejected(auth_client):
    resp = auth_client.post(URL, json=_payload())
    assert resp.status_code == 401
    assert resp.json()["code"] == "AUTH_REQUIRED"


def test_auth_enabled_wrong_token_rejected(auth_client):
    resp = auth_client.post(
        URL,
        json=_payload(),
        headers={"Authorization": "Bearer wrong-token"},
    )
    assert resp.status_code == 401
    assert resp.json()["code"] == "AUTH_INVALID"


def test_auth_enabled_correct_token_passes(auth_client, fake_client):
    fake_client.set_script(make_success_body([make_chunk(0, "A")]))
    resp = auth_client.post(
        URL,
        json=_payload(),
        headers={"Authorization": "Bearer secret-token-1"},
    )
    assert resp.status_code == 200
    assert resp.json()["code"] == 200


def test_auth_enabled_second_token_passes(auth_client, fake_client):
    fake_client.set_script(make_success_body([make_chunk(0, "A")]))
    resp = auth_client.post(
        URL,
        json=_payload(),
        headers={"Authorization": "Bearer secret-token-2"},
    )
    assert resp.status_code == 200


def test_auth_enabled_malformed_header_rejected(auth_client):
    """非 Bearer 前缀的 header 视为缺失凭据。"""
    resp = auth_client.post(
        URL,
        json=_payload(),
        headers={"Authorization": "Basic abc"},
    )
    assert resp.status_code == 401


def test_error_response_does_not_leak_token(auth_client, caplog):
    """鉴权失败的错误响应体不应包含任何 token 信息。"""
    resp = auth_client.post(
        URL,
        json=_payload(),
        headers={"Authorization": "Bearer secret-token-1"},
    )
    # 这里用错 token 让其失败（不带正确 token）
    body = resp.text
    assert "secret-token" not in body


# =====================================================================
# request_id 透传 / 自动生成
# =====================================================================

def test_request_id_passthrough(client, fake_client):
    """request_id 放在 options.request_id 中透传。"""
    fake_client.set_script(make_success_body([make_chunk(0, "A")]))
    resp = client.post(URL, json={
        "query": "a.docx",
        "options": {"request_id": "my-custom-id"},
    })
    assert resp.status_code == 200
    assert resp.json()["request_id"] == "my-custom-id"


def test_request_id_autogenerated(client, fake_client):
    fake_client.set_script(make_success_body([make_chunk(0, "A")]))
    resp = client.post(URL, json=_payload())
    assert resp.status_code == 200
    rid = resp.json()["request_id"]
    assert rid is not None
    assert rid.startswith("srv_")  # 自动生成前缀
